steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/carbon-vasi-951/carbon-repo/api:latest', '-f', 'apps/api/Dockerfile', '.']
images:
- 'us-central1-docker.pkg.dev/carbon-vasi-951/carbon-repo/api:latest'
